# Generated by Django 5.0 on 2023-12-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TunShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default='empty', max_length=50, null=True),
        ),
    ]
