# Generated by Django 5.0 on 2023-12-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TunShopApp', '0002_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
