# Generated by Django 5.0 on 2023-12-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TunShopApp', '0007_alter_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.BigIntegerField(),
        ),
    ]
