# Generated by Django 5.0 on 2023-12-21 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TunShopApp', '0009_alter_cartitem_quantity_alter_cartitem_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='TunShopApp.product'),
        ),
    ]
