# Generated by Django 5.0 on 2023-12-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TunShopApp', '0011_wishlist_quantity_alter_wishlist_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
