# Generated by Django 5.0 on 2023-12-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TunShopApp', '0012_remove_wishlist_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.TextField(),
        ),
    ]
