# Generated by Django 5.0 on 2023-12-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TunShopApp', '0013_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='total_amount',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
