# Generated by Django 5.0 on 2023-12-21 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TunShopApp', '0014_orderlist_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
