# Generated by Django 5.0 on 2023-12-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TunShopApp', '0015_userregistrationmodel_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
