# Generated by Django 5.0 on 2023-12-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TunShopApp', '0016_alter_orderlist_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='caroselslider')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='caroselslider')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='caroselslider')),
            ],
        ),
    ]
