# Generated by Django 4.2.6 on 2023-12-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_cartitem_total_alter_cartitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product', null='True', on_delete=django.db.models.deletion.CASCADE, to='userapp.product')),
            ],
        ),
    ]
